# Generated by Django 4.2.7 on 2025-09-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='使用者名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理員')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_code', models.CharField(max_length=8, unique=True, verbose_name='教練編號')),
                ('name', models.CharField(max_length=50, verbose_name='教練姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手機號碼')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('status', models.CharField(choices=[('active', '啟用'), ('inactive', '停用')], default='active', max_length=10, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '教練',
                'verbose_name_plural': '教練',
                'db_table': 'coaches',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=8, unique=True, verbose_name='會員編號')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手機號碼')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, null=True, verbose_name='性別')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='緊急聯絡人姓名')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=30, null=True, verbose_name='緊急聯絡人關係')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='緊急聯絡人電話')),
                ('registration_date', models.DateField(verbose_name='註冊日期')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('status', models.CharField(choices=[('active', '啟用'), ('inactive', '停用')], default='active', max_length=10, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.coach', verbose_name='負責教練')),
            ],
            options={
                'verbose_name': '會員',
                'verbose_name_plural': '會員',
                'db_table': 'members',
            },
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['phone'], name='coaches_phone_c600d8_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='members_phone_c64f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['coach'], name='members_coach_i_e211d1_idx'),
        ),
    ]
