# Generated by Django 4.2.7 on 2025-09-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='手機號碼'),
        ),
    ]
