# Generated by Django 4.2.7 on 2025-09-08 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('module', models.CharField(max_length=50, verbose_name='功能模組')),
                ('operation_content', models.TextField(verbose_name='操作內容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '操作日誌',
                'verbose_name_plural': '操作日誌',
                'db_table': 'operation_logs',
                'indexes': [models.Index(fields=['operation_time'], name='operation_l_operati_1d2f3a_idx'), models.Index(fields=['module'], name='operation_l_module_00a396_idx')],
            },
        ),
    ]
