# Generated by Django 4.2.7 on 2025-09-08 07:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='系統自動產生，格式：CR + 6位數字', max_length=8, unique=True, verbose_name='課程編號')),
                ('name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('quantity_options', models.TextField(blank=True, help_text='以逗號分隔的數字，例如：3,5,8', validators=[core.models.validate_comma_separated_numbers], verbose_name='數量選項')),
                ('price_options', models.TextField(blank=True, help_text='以逗號分隔的數字，例如：1000,1500,2000', validators=[core.models.validate_comma_separated_numbers], verbose_name='單價選項')),
                ('unlimited_quantity', models.BooleanField(default=False, verbose_name='不限制數量')),
                ('unlimited_price', models.BooleanField(default=False, verbose_name='不限制單價')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('status', models.CharField(choices=[('active', '啟用'), ('inactive', '停用')], default='active', max_length=10, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'db_table': 'courses',
            },
        ),
    ]
