# Generated by Django 4.2.10 on 2025-09-09 03:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_member_phone'),
        ('core', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(help_text='系統自動產生，格式：O + 6位數字', max_length=8, unique=True, verbose_name='訂單編號')),
                ('order_date', models.DateField(help_text='訂單建立日期', verbose_name='訂單日期')),
                ('payment_method', models.CharField(choices=[('cash', '現金'), ('card', '刷卡'), ('transfer', '轉帳')], max_length=10, verbose_name='付款方式')),
                ('order_status', models.CharField(choices=[('paid', '已付款'), ('unpaid', '未付款'), ('cancelled', '已取消')], default='unpaid', max_length=10, verbose_name='訂單狀態')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='總金額')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.member', verbose_name='會員')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CourseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.PositiveIntegerField(help_text='購買時的數量', verbose_name='初始數量')),
                ('remaining_quantity', models.PositiveIntegerField(help_text='剩餘可使用的數量', verbose_name='剩餘數量')),
                ('status', models.CharField(choices=[('active', '啟用'), ('used_up', '已用完')], default='active', max_length=10, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='core.course', verbose_name='課程')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_inventories', to='accounts.member', verbose_name='會員')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_inventories', to='core.order', verbose_name='訂單')),
            ],
            options={
                'verbose_name': '課程庫存',
                'verbose_name_plural': '課程庫存',
                'db_table': 'course_inventory',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('course', '課程'), ('product', '商品')], max_length=10, verbose_name='項目類型')),
                ('item_id', models.PositiveIntegerField(help_text='課程或商品的ID', verbose_name='項目ID')),
                ('quantity', models.PositiveIntegerField(help_text='購買數量', verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='單價', max_digits=10, verbose_name='單價')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='總價（數量 × 單價）', max_digits=10, verbose_name='總價')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.order', verbose_name='訂單')),
            ],
            options={
                'verbose_name': '訂單明細',
                'verbose_name_plural': '訂單明細',
                'db_table': 'order_items',
                'indexes': [models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'), models.Index(fields=['item_type', 'item_id'], name='order_items_item_ty_3ebb0c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['member'], name='orders_member__f73a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='orders_order_d_6e39a9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='orders_order_s_0d3802_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinventory',
            index=models.Index(fields=['member'], name='course_inve_member__fd9d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinventory',
            index=models.Index(fields=['course'], name='course_inve_course__863e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinventory',
            index=models.Index(fields=['order'], name='course_inve_order_i_6d0e89_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinventory',
            index=models.Index(fields=['status'], name='course_inve_status_ab2bf7_idx'),
        ),
    ]
