# Generated by Django 4.2.7 on 2025-09-11 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_order_courseinventory_orderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(help_text='系統自動產生，格式：S + 6位數字', max_length=8, unique=True, verbose_name='授課編號')),
                ('session_date', models.DateField(default=django.utils.timezone.now, verbose_name='授課日期')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='accounts.coach', verbose_name='教練')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.course', verbose_name='課程')),
                ('course_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.courseinventory', verbose_name='課程庫存')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sessions', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='accounts.member', verbose_name='會員')),
            ],
            options={
                'verbose_name': '授課紀錄',
                'verbose_name_plural': '授課紀錄',
                'db_table': 'sessions',
                'indexes': [models.Index(fields=['member'], name='sessions_member__3c7673_idx'), models.Index(fields=['coach'], name='sessions_coach_i_ce3bf5_idx'), models.Index(fields=['session_date'], name='sessions_session_dddd91_idx')],
            },
        ),
    ]
