# Generated by Django 4.2.7 on 2025-10-13 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_add_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='庫存數量，可為負數（表示缺貨狀態）', verbose_name='庫存數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_inventories', to=settings.AUTH_USER_MODEL, verbose_name='最後更新者')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品庫存',
                'verbose_name_plural': '商品庫存',
                'db_table': 'product_inventory',
                'indexes': [models.Index(fields=['product'], name='product_inv_product_d3d381_idx'), models.Index(fields=['quantity'], name='product_inv_quantit_a03c94_idx')],
            },
        ),
    ]
