# Generated by Django 4.2.10 on 2026-01-16 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_phone'),
        ('core', '0006_add_product_inventory_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='accounts.coach', verbose_name='上課教練'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='授課日期與時間'),
        ),
    ]
